Bell to AArch64

"r[plain] %x %y" -> "LDR %x,[%y]"

"r[plain] %x y" -> "LDR %x,[%y]"

"r[acq] %x y" -> "LDAR %x,[%y]"

"w[plain] %x &c" -> "MOV %tmp,&c;
                     STR %tmp,[%x]"

"w[plain] x &c" -> "MOV %tmp,&c;
                    STR %tmp,[%x]"

"w[plain] %x %y" -> "STR %x,[%y]"

"w[rel] x &c" -> "MOV %tmp,&c;
	          STLR %tmp,[%x]"

"f[dmb,all,sy]" -> "DMB SY"

"f[dmb,ld,sy]" -> "DMB LD"

"f[dmb,st,sy]" -> "DMB ST"