(lang dune 3.10)
(name aslspec)
(using menhir 2.0)
(cram enable)

(package
 (name aslspec)
 (synopsis "Architecture Specification Language Semantics Specification Tool")
 (depends
   (ocaml (>= 4.08))
   dune
   (menhir (>= 20220210))
   (conf-python-3 (= 9.0.0))))

