  $ uoaim7 --def -set-libdir ./libdir data/bad/bad01.txt
  Interpretation error: definition preamble must mention exactly two effects, with the phrasing "an Effect En" for natural number `n`.
    Context: "there is a relation from E1 to an E2"
  $ uoaim7 --def -set-libdir ./libdir data/bad/bad02.txt
  Parse error: invalid connective phrase "all of the following".
  At line 1: "There is a relation from an Effect E1 to an Effect E2 if and only if all of the following:"
  $ uoaim7 --def -set-libdir ./libdir data/bad/bad03.txt
  Parse error: expected bullet point of level 2 but got "* E1 and E...".
  At line 4: "* E1 and E2 are generated by the same instruction."
  $ uoaim7 --def -set-libdir ./libdir data/bad/bad04.txt
  Parse error: when parsing constraint termination symbol: expected character '.' but got '*'.
  At line 2: "* E1 is a Memory Effect."
  $ uoaim7 --def -set-libdir ./libdir data/bad/bad05.txt
  Parse error: when parsing constraint termination symbol: expected character '.' but got '*'.
  At line 3: "* E1 and E2 are generated by the same instruction."
  $ uoaim7 --def -set-libdir ./libdir data/bad/bad06.txt
  Parse error: when parsing constraint termination symbol: expected character '.' but got '%'.
  At line 3: "* E1 and E2 are %$# by the same instruction."
  $ uoaim7 --def -set-libdir ./libdir data/bad/bad07.txt
  Parse error: expected end of input but got "** E1 and ...".
  At line 3: "** E1 and E2 are generated by the same instruction."
