record = "AArch64 GICv5"

cats = [
    "cats/aarch64.cat"
]

cfgs = [
    "cfgs/web.cfg",
]

illustrative_tests = [
    "tests/IRIW-2loc+gic.cdpri.litmus",
    "tests/IRIW-loc+gic.cdpri.litmus",
    "tests/MP+gsb.sys+dsb.ld.litmus",
    "tests/MP-fDI+RR.litmus",
    "tests/MP-fDI+W-dsb-W+R-addrpt-R.litmus",
    "tests/MP-fDI+W-dsb-W+R-ctrlisb-R.litmus",
    "tests/MP-fDI+W-dsb-W+R-gsb-R.litmus",
    "tests/MP-fDI+W-dsb-W+RR.litmus",
    "tests/MP-fDI+WW+R-gsb-R.litmus",
#    "tests/MP-fDI+ack-DI+gic.dis-R-gsb.sys-mR.litmus",
#    "tests/MP-fDI+ack-DSB-DI+gic.dis-R-gsb.sys-mR.litmus",
    "tests/MP-fIPI+dsb.st+addr.litmus",
    "tests/MP-fIPI+dsb.st+ctrlisb.litmus",
    "tests/MP-fIPI+dsb.st+gsb.ack.litmus",
    "tests/MP-fIPI-dTag+dsb.st+gsb.ack.litmus",
#    "tests/MP-fLPI+imp+addrpt.litmus",
#    "tests/MP-fLPI+imp+gsb.ack.litmus",
#    "tests/MP-fSPI+dsb.st+gsb.ack.litmus",
    "tests/MP-gic+dis-gsb.sys+dsb.ld.litmus",
#    "tests/MP-pri+gsb.sys+ack.litmus",
#    "tests/Wvm-gic+R.litmus",
    "tests/ack-deactivate.litmus",
    "tests/atomic-gic.ack.litmus",
    "tests/atomic.ack.dis.gic+W+R.litmus",
    "tests/atomic.ack.gic-ib+W-R-si-R.litmus",
    "tests/co.ack-gic+WP+ack+ack.litmus",
#    "tests/co.ack.1ofN-gic.litmus",
#    "tests/coRR+gic.cddis+gic.cdrcfg-clr.i-isb.litmus",
#    "tests/coRR+gic.cddis+gic.cdrcfg-isb-clr.i.litmus",
    "tests/coRR-gic+cdpri+cfg-isb-cfg-isb.litmus",
    "tests/coRR.ack+dis+Rack.litmus",
    "tests/coRR.ack.litmus",
    "tests/coRW-gic+rcfg-di.litmus",
    "tests/coRW-gic+rcfg-ia.litmus",
    "tests/coRW-gic+rcfg-pri.litmus",
#    "tests/coRex-gic+dis+RR.litmus",
#    "tests/coRex-gic+dis+RisbR.litmus",
#    "tests/coWR+gic.cden-gsb.sys-isb-isr+wait.litmus",
#    "tests/coWR+gic.cden-gsb.sys-isb-isr.litmus",
    "tests/coWR-gic+di-rcfg.litmus",
    "tests/coWR-gic+dis-gsb.sys-ia.litmus",
    "tests/coWR-gic+en-rcfg.litmus",
    "tests/coWR-gic+ia-gsb.ack-di.litmus",
    "tests/coWR-gic+ia-rcfg.litmus",
    "tests/coWR-gic.dis.ack+gsb.sys.litmus",
    "tests/coWR-gic.dis.ack.litmus",
    "tests/coWR-gic.ipi.ack+gsb.sys.litmus",
    "tests/coWR-gic.ipi.ack.litmus",
    "tests/coWR-gic.litmus",
    "tests/coWRW-gic.litmus",
    "tests/coWW-gic+R.litmus",
    "tests/coWW-gic+di-ia+rcfg.litmus",
    "tests/coWW-gic+di-pri+rcfg.litmus",
    "tests/coWW-gic.litmus",
    "tests/coWW-gic+di-pend1.litmus",
    "tests/coWW-gic+dis-ia.litmus",
    "tests/coWW.ack-gic+WP+ack.litmus",
    "tests/coWWR-gic+pri-di-nmia.litmus",
    "tests/coWWR-gic+pri-pend1-nmia.litmus",
#    "tests/coWWW-gic.dis-en+ack+ack.litmus",
#    "tests/coWex+gic.cddis-gsb.sys-clr.i.litmus",
#    "tests/coWex+gic.cddis-gsb.sys-isb-clr.i.litmus",
#    "tests/coWmrs.ack+gsb.litmus",
#    "tests/coWmrs.ack+isb.litmus",
#    "tests/coWmrs.ack.litmus",
#    "tests/comsrR.ack+isb.litmus",
#    "tests/edge-merging.LPI+gsb.ack.litmus",
    "tests/edge-merging.ipi.MP.litmus",
#    "tests/edge-merging.ipi.litmus",
#    "tests/edge-merging.ppi.litmus",
    "tests/gic.pri+gic.en.litmus",
#    "tests/vmW-gic+R.litmus",
]
