record = "AArch64-Pick"


cats = [
  "cats/aarch64.cat",
  ]

cfgs = [
    "cfgs/new-web.cfg",
]

illustrative_tests = [
    "tests/MP+rel+CAS-addr.litmus",
    "tests/MP+rel+CSEL-addr.litmus",
    "tests/MP+rel+CSEL-addr2.litmus",
    "tests/LB+rel+CAS.litmus",
    "tests/LB+CSEL-rfi-data+DMB.litmus",
    "tests/S+rel+CSEL-data.litmus",
#    "tests/S+rel+CSEL-data2.litmus",
    "tests/MP+CSEL-rfi-addr-rfi-addr.litmus",
    "tests/LB+CSEL-addr-po+DMB.litmus",
    "tests/LB+CSEL-data-po+DMB.litmus",
#    "tests/MP+rel+CSEL-rfi-data-rfi-addr.litmus",
#    "tests/S+rel+CSEL-rfi-data-rfi-addr.litmus",
#    "tests/S+rel+CSEL-rfi-ctrl.litmus",
    "tests/T3.litmus",
    "tests/T3-bis.litmus",
#    "tests/S+DMB.ST+CSEL-ctrl.litmus",
    "tests/LB+rel+data.litmus",
    "tests/S+rel+CSEL.litmus",
    "tests/S+rel+CSEL-rf-reg.litmus",
    "tests/T7.litmus",
    "tests/T7dep.litmus",
    "tests/T8.litmus",
    "tests/T8+BIS.litmus",
    "tests/T9.litmus",
    "tests/T9B.litmus",
    "tests/T9C.litmus",
    "tests/T10B.litmus",
    "tests/T10C.litmus",
    "tests/T11.litmus",
    "tests/T12.litmus",
    "tests/T12B.litmus",
    "tests/T13.litmus",
    "tests/T13B.litmus",
    "tests/T13-mod2.litmus",
    "tests/T13-mod3.litmus",
    "tests/T13-mod4.litmus",
    "tests/T14.litmus",
    "tests/T14B.litmus",
    "tests/T14B-corrected.litmus",
    "tests/T14-controldep.litmus",
    "tests/T14B-controldep.litmus",
    "tests/TLDAR.litmus",
    "tests/Pick3.litmus",
    "tests/Pick3-mod.litmus",
    "tests/T99.litmus",
    "tests/T99-excls.litmus",
    "tests/T99-excls-RZR.litmus",
    "tests/T99-STADD.litmus",
    "tests/Pick0.litmus",
    "tests/Pick1.litmus",
    "tests/Pick2.litmus",
    "tests/Pick2-noWZR.litmus",
    "tests/T15-corrected.litmus",
    "tests/T15-datadep-corrected.litmus",
    "tests/LB+rel+pick-by-csel.litmus",
    "tests/LB+rel+CSEL-CSEL.litmus",
]
