(*
 * SPDX-FileCopyrightText: Copyright 2022-2023 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: BSD-3-Clause
 *)
(*
    **DISCLAIMER**: The ASL reference implementation can be found in `herdtools7/asllib`. This tool and any files generated by it are **NOT** a reference ASL implementation!
    Modifications of generated files will lead to an **UNSUPPORTED** divergence from the reference implementation and should **NOT** be done!
*)

(* Definitions for various common utility functions and modules *)

(* Simple StringMap/StringSet definitions *)
module StringMap = Map.Make (String)
module StringSet = Set.Make (String)

(** A copy of Ocaml's List.find_index from stdlib 5.1
    https://github.com/ocaml/ocaml/blob/trunk/stdlib/list.ml *)
let list_find_index p =
  let rec aux i = function
    | [] -> None
    | a :: l -> if p a then Some i else aux (i + 1) l
  in
  aux 0

(* I/O utility functions *)
let with_open_in_bin file fn =
  let chan = open_in_bin file in
  let res = fn chan in
  close_in chan;
  res

let with_open_out_bin file fn =
  let chan = open_out_bin file in
  fn chan;
  close_out chan
