Run litmus2desc on small AArch64 tests containing barrier instructions.

  $ for f in $(LC_ALL=C ls -1 barrier_litmus_tests | sort); do
  >   echo "== $f =="; echo;
  >   litmus2desc -set-libdir ./libdir --describe-dep-path "barrier_litmus_tests/$f"; echo;
  > done
  == LB+dmb.sys.litmus ==
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The Load instruction on P0, i.e. LDR W0,[X1], generates an Explicit Memory Read Effect of Location x;
  * The DMB SY instruction on P0 generates a DMB.FULL Effect;
  * The Store instruction on P0, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The Load instruction on P1, i.e. LDR W0,[X1], generates an Explicit Memory Read Effect of Location y;
  * The DMB SY instruction on P1 generates a DMB.FULL Effect;
  * The Store instruction on P1, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location x with value 1;
  * The Register X0 on P0 holds the value 1 in the end, because the Explicit Memory Read Effect on P0 Reads-from the Explicit Memory Write Effect on P1;
  * The Register X0 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect on P1 Reads-from the Explicit Memory Write Effect on P0.
  
  == MP+dmb.sys.litmus ==
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The DMB SY instruction on P0 generates a DMB.FULL Effect;
  * The second Store instruction in program order on P0, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The first Load instruction in program order on P1, i.e. LDR W0,[X1], generates an Explicit Memory Read Effect of Location y;
  * The DMB SY instruction on P1 generates a DMB.FULL Effect;
  * The second Load instruction in program order on P1, i.e. LDR W2,[X3], generates an Explicit Memory Read Effect of Location x;
  * The Register X0 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location y on P1 generated by LDR W0,[X1] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STR W2,[X3];
  * The Register X2 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W2,[X3] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1].
  
  == SB+dmb.sy+po.litmus ==
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The Store instruction on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The DMB SY instruction on P0 generates a DMB.FULL Effect;
  * The Load instruction on P0, i.e. LDR W2,[X3], generates an Explicit Memory Read Effect of Location y;
  * The Store instruction on P1, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location y with value 1;
  * The Load instruction on P1, i.e. LDR W2,[X3], generates an Explicit Memory Read Effect of Location x;
  * The Register X2 on P0 holds the value 0 in the end, because the Explicit Memory Read Effect on P0 Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect on P1;
  * The Register X2 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect on P1 Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect on P0.
  
