  $ litmus2desc -set-libdir ./libdir --latex litmus_tests/MP.litmus
  This test asks whether the following execution is architecturally Allowed:
  
  \begin{itemize}
    \item The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
    \item The second Store instruction in program order on P0, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
    \item The first Load instruction in program order on P1, i.e. LDR W4,[X3], generates an Explicit Memory Read Effect of Location y;
    \item The second Load instruction in program order on P1, i.e. LDR W6,[X1], generates an Explicit Memory Read Effect of Location x;
    \item The Register X4 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location y on P1 generated by LDR W4,[X3] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STR W2,[X3];
    \item The Register X6 on P1 holds the value 0 in the end, which means that the Explicit Memory Read Effect of Location x on P1 generated by LDR W6,[X1] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1].
  \end{itemize}
  $ litmus2desc -set-libdir ./libdir --latex litmus_tests/MP+poll+poaa-amo.casal-pola.litmus
  This test asks whether one of the following candidate executions is architecturally Allowed:
  
  \paragraph{First execution}
  
  \begin{itemize}
    \item The first Store Release instruction in program order on P0, i.e. STLR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
    \item The second Store Release instruction in program order on P0, i.e. STLR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
    \item The first Load Acquire instruction in program order on P1, i.e. LDAR W1,[X0], generates an Explicit Memory Read Effect of Location y;
    \item The CASAL instruction on P1, i.e. CASAL W3,W4,[X2], generates an Explicit Memory Read Effect of Location z;
    \item The CASAL instruction on P1, i.e. CASAL W3,W4,[X2], generates an Explicit Memory Write Effect of Location z with value 1;
    \item The second Load Acquire instruction in program order on P1, i.e. LDAR W6,[X5], generates an Explicit Memory Read Effect of Location x;
    \item The Register X1 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location y on P1 generated by LDAR W1,[X0] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STLR W2,[X3];
    \item The Register X3 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location z on P1 generated by CASAL W3,W4,[X2] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect on P1;
    \item The Register X6 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDAR W6,[X5] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STLR W0,[X1].
  \end{itemize}
  
  \paragraph{Second execution}
  
  \begin{itemize}
    \item The first Store Release instruction in program order on P0, i.e. STLR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
    \item The second Store Release instruction in program order on P0, i.e. STLR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
    \item The first Load Acquire instruction in program order on P1, i.e. LDAR W1,[X0], generates an Explicit Memory Read Effect of Location y;
    \item The CASAL instruction on P1, i.e. CASAL W3,W4,[X2], generates an Explicit Memory Read Effect of Location z;
    \item The CASAL instruction on P1, i.e. CASAL W3,W4,[X2], generates an Explicit Memory Write Effect of Location z with value 1;
    \item The second Load Acquire instruction in program order on P1, i.e. LDAR W6,[X5], generates an Explicit Memory Read Effect of Location x;
    \item The Register X1 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location y on P1 generated by LDAR W1,[X0] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STLR W2,[X3];
    \item The Register X3 on P1 holds the value 0 in the end, because the Register Read Effect originating from the CASAL instruction on P1 has read the value 0 from the Register Write Effect originating from the MOV instruction on P1;
    \item The Register X6 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDAR W6,[X5] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STLR W0,[X1].
  \end{itemize}
  $ litmus2desc -set-libdir ./libdir --latex litmus_tests/PPODA.litmus
  This test asks whether the following execution is architecturally Allowed:
  
  \begin{itemize}
    \item The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
    \item The second Store instruction in program order on P0, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
    \item The first Load instruction in program order on P1, i.e. LDR W0,[X3], generates an Explicit Memory Read Effect of Location y;
    \item The first Exclusive Or instruction in program order on P1, i.e. EOR W2,W0,W0, and the Add instruction on P1, i.e. ADD W2,W2,\#1, create a Data dependency from the first Load instruction in program order on P1, i.e. LDR W0,[X3], to the Store instruction on P1, i.e. STR W2,[X4];
    \item The Store instruction on P1, i.e. STR W2,[X4], generates an Explicit Memory Write Effect of Location z with value 1;
    \item The second Load instruction in program order on P1, i.e. LDR W5,[X4], generates an Explicit Memory Read Effect of Location z;
    \item The second Exclusive Or instruction in program order on P1, i.e. EOR W6,W5,W5, creates an Address dependency from the second Load instruction in program order on P1, i.e. LDR W5,[X4], to the third Load instruction in program order on P1, i.e. LDR W7,[X1,W6,SXTW];
    \item The third Load instruction in program order on P1, i.e. LDR W7,[X1,W6,SXTW], generates an Explicit Memory Read Effect of Location x;
    \item The Register X0 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location y on P1 generated by LDR W0,[X3] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STR W2,[X3];
    \item The Register X5 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location z on P1 generated by LDR W5,[X4] Reads-from the Explicit Memory Write Effect on P1;
    \item The Register X7 on P1 holds the value 0 in the end, which means that the Explicit Memory Read Effect of Location x on P1 generated by LDR W7,[X1,W6,SXTW] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1].
  \end{itemize}
