Run litmus2desc on MP+poll+poaa-amo.casal-pola.

  $ cat other_litmus_tests/MP+poll+poaa-amo.casal-pola.litmus; echo
  AArch64 MP+poll+poaa-amo.casal-pola
  {
  0:X1=x; 0:X3=y;
  1:X0=y; 1:X2=z; 1:X5=x;
  }
   P0           | P1               ;
   MOV W0,#1    | LDAR W1,[X0]     ;
   STLR W0,[X1] | MOV W3,#0        ;
   MOV W2,#1    | MOV W4,#1        ;
   STLR W2,[X3] | CASAL W3,W4,[X2] ;
                | LDAR W6,[X5]     ;
  exists (1:X1=1 /\ 1:X3=0 /\ 1:X6=0)
  
  $ litmus2desc -set-libdir ./libdir --describe-dep-path other_litmus_tests/MP+poll+poaa-amo.casal-pola.litmus
  This test asks whether one of the following candidate executions is architecturally Allowed:
  
  === First execution ===
  
  * The first Store Release instruction in program order on P0, i.e. STLR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store Release instruction in program order on P0, i.e. STLR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The first Load Acquire instruction in program order on P1, i.e. LDAR W1,[X0], generates an Explicit Memory Read Effect of Location y;
  * The CASAL instruction on P1, i.e. CASAL W3,W4,[X2], generates an Explicit Memory Read Effect of Location z, and an Explicit Memory Write Effect of Location z with value 1;
  * The second Load Acquire instruction in program order on P1, i.e. LDAR W6,[X5], generates an Explicit Memory Read Effect of Location x;
  * The Register X1 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location y on P1 generated by LDAR W1,[X0] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STLR W2,[X3];
  * The Register X3 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location z on P1 generated by CASAL W3,W4,[X2] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect on P1;
  * The Register X6 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDAR W6,[X5] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STLR W0,[X1].
  
  === Second execution ===
  
  * The first Store Release instruction in program order on P0, i.e. STLR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store Release instruction in program order on P0, i.e. STLR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The first Load Acquire instruction in program order on P1, i.e. LDAR W1,[X0], generates an Explicit Memory Read Effect of Location y;
  * The CASAL instruction on P1, i.e. CASAL W3,W4,[X2], generates an Explicit Memory Read Effect of Location z, and an Explicit Memory Write Effect of Location z with value 1;
  * The second Load Acquire instruction in program order on P1, i.e. LDAR W6,[X5], generates an Explicit Memory Read Effect of Location x;
  * The Register X1 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location y on P1 generated by LDAR W1,[X0] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STLR W2,[X3];
  * The Register X3 on P1 holds the value 0 in the end, because the Register Read Effect originating from the CASAL instruction on P1 has read the value 0 from the Register Write Effect originating from the MOV instruction on P1;
  * The Register X6 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDAR W6,[X5] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STLR W0,[X1].
