Check output from litmus test with multiple candidate executions satisfying the post-condition

  $ cat other_litmus_tests/multi_execs.litmus; echo
  AArch64 multi_execs
  {
  0:X1=x;
  1:X0=x;
  }
   P0          | P1          ;
   MOV W0,#1   | LDR W1,[X0] ;
   STR W0,[X1] | LDR W2,[X0] ;
   MOV W2,#1   | LDR W3,[X0] ;
   STR W2,[X1] |             ;
   MOV W3,#3   |             ;
   STR W3,[X1] |             ;
  exists ([x]=3 /\ 1:X1=3 /\ 1:X2=1 /\ 1:X3=0)
  
  $ litmus2desc -set-libdir ./libdir --describe-dep-path other_litmus_tests/multi_execs.litmus
  This test asks whether one of the following candidate executions is architecturally Allowed:
  
  === First execution ===
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The third Store instruction in program order on P0, i.e. STR W3,[X1], generates an Explicit Memory Write Effect of Location x with value 3;
  * The first Load instruction in program order on P1, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The second Load instruction in program order on P1, i.e. LDR W2,[X0], generates an Explicit Memory Read Effect of Location x;
  * The third Load instruction in program order on P1, i.e. LDR W3,[X0], generates an Explicit Memory Read Effect of Location x;
  * The value of x is 3 in the end, because the Explicit Memory Write Effect of Location x on P0 generated by STR W2,[X1] is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X1 on P1 holds the value 3 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W1,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X2 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W2,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W2,[X1];
  * The Register X3 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W3,[X0] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1].
  
  === Second execution ===
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The third Store instruction in program order on P0, i.e. STR W3,[X1], generates an Explicit Memory Write Effect of Location x with value 3;
  * The first Load instruction in program order on P1, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The second Load instruction in program order on P1, i.e. LDR W2,[X0], generates an Explicit Memory Read Effect of Location x;
  * The third Load instruction in program order on P1, i.e. LDR W3,[X0], generates an Explicit Memory Read Effect of Location x;
  * The value of x is 3 in the end, because the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1] is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X1 on P1 holds the value 3 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W1,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X2 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W2,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W2,[X1];
  * The Register X3 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W3,[X0] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W2,[X1].
  
  === Third execution ===
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The third Store instruction in program order on P0, i.e. STR W3,[X1], generates an Explicit Memory Write Effect of Location x with value 3;
  * The first Load instruction in program order on P1, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The second Load instruction in program order on P1, i.e. LDR W2,[X0], generates an Explicit Memory Read Effect of Location x;
  * The third Load instruction in program order on P1, i.e. LDR W3,[X0], generates an Explicit Memory Read Effect of Location x;
  * The value of x is 3 in the end, because the Explicit Memory Write Effect of Location x on P0 generated by STR W2,[X1] is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X1 on P1 holds the value 3 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W1,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X2 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W2,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1];
  * The Register X3 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W3,[X0] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1].
  
  === Fourth execution ===
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The third Store instruction in program order on P0, i.e. STR W3,[X1], generates an Explicit Memory Write Effect of Location x with value 3;
  * The first Load instruction in program order on P1, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The second Load instruction in program order on P1, i.e. LDR W2,[X0], generates an Explicit Memory Read Effect of Location x;
  * The third Load instruction in program order on P1, i.e. LDR W3,[X0], generates an Explicit Memory Read Effect of Location x;
  * The value of x is 3 in the end, because the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1] is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X1 on P1 holds the value 3 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W1,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X2 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W2,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1];
  * The Register X3 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W3,[X0] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W2,[X1].
