Run litmus2desc on all tests in sorted order and compare output.

  $ for f in $(LC_ALL=C ls -1 litmus_tests | sort); do
  >   echo "== $f =="; echo;
  >   cat "litmus_tests/$f"; echo;
  >   litmus2desc -set-libdir ./libdir "litmus_tests/$f"; echo;
  > done
  == CoRR.litmus ==
  
  AArch64 CoRR
  {
  0:X1=x;
  1:X0=x;
  }
   P0          | P1          ;
   MOV W0,#1   | LDR W1,[X0] ;
   STR W0,[X1] | LDR W2,[X0] ;
  exists (1:X1=1 /\ 1:X2=0)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The Store instruction on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The first Load instruction in program order on P1, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The second Load instruction in program order on P1, i.e. LDR W2,[X0], generates an Explicit Memory Read Effect of Location x;
  * The Register X1 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location x on P1 generated by LDR W1,[X0] Reads-from the Explicit Memory Write Effect on P0;
  * The Register X2 on P1 holds the value 0 in the end, which means that the Explicit Memory Read Effect of Location x on P1 generated by LDR W2,[X0] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect on P0.
  
  == CoRW1.litmus ==
  
  AArch64 CoRW1
  { 0:X0=x; }
   P0          ;
   LDR W1,[X0] ;
   MOV W2,#1   ;
   STR W2,[X0] ;
  exists (0:X1=1)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The Load instruction on P0, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The Store instruction on P0, i.e. STR W2,[X0], generates an Explicit Memory Write Effect of Location x with value 1;
  * The Register X1 on P0 holds the value 1 in the end, which means that the Explicit Memory Read Effect Reads-from the Explicit Memory Write Effect.
  
  == CoRW2.litmus ==
  
  AArch64 A
  "PosRW Coe Rfe"
  Generator=diyone7 (version 7.58)
  Com=Co Rf
  Orig=PosRW Coe Rfe
  {
  0:X0=x;
  1:X0=x;
  }
   P0          | P1          ;
   LDR W1,[X0] | MOV W1,#2   ;
   MOV W2,#1   | STR W1,[X0] ;
   STR W2,[X0] |             ;
  exists ([x]=2 /\ 0:X1=2)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The Load instruction on P0, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The Store instruction on P0, i.e. STR W2,[X0], generates an Explicit Memory Write Effect of Location x with value 1;
  * The Store instruction on P1, i.e. STR W1,[X0], generates an Explicit Memory Write Effect of Location x with value 2;
  * The value of x is 2 in the end, which means that the Explicit Memory Write Effect on P0 is Coherence-before the Explicit Memory Write Effect on P1;
  * The Register X1 on P0 holds the value 2 in the end, which means that the Explicit Memory Read Effect on P0 Reads-from the Explicit Memory Write Effect on P1.
  
  == CoWR.litmus ==
  
  AArch64 CoWR
  { 0:X1=x; }
   P0          ;
   MOV W0,#1   ;
   STR W0,[X1] ;
   LDR W2,[X1] ;
  exists (x=1 /\ 0:X2=0)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The Store instruction on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The Load instruction on P0, i.e. LDR W2,[X1], generates an Explicit Memory Read Effect of Location x;
  * The value of x is 1 in the end, which means that the Store instruction on P0 has updated the memory;
  * The Register X2 on P0 holds the value 0 in the end, which means that the Explicit Memory Read Effect Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect.
  
  == CoWW.litmus ==
  
  AArch64 CoWW
  { 0:X1=x; }
   P0          ;
   MOV W0,#2   ;
   STR W0,[X1] ;
   MOV W2,#1   ;
   STR W2,[X1] ;
  exists ([x]=2)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 2;
  * The second Store instruction in program order on P0, i.e. STR W2,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The value of x is 2 in the end, which means that the Explicit Memory Write Effect of Location x generated by STR W2,[X1] is Coherence-before the Explicit Memory Write Effect of Location x generated by STR W0,[X1].
  
  == ISA2.litmus ==
  
  AArch64 ISA2
  {
  0:X1=x; 0:X3=y;
  1:X3=y; 1:X6=z;
  2:X6=z; 2:X1=x;
  }
  P0          | P1          | P2          ;
  MOV W0,#1   | LDR W4,[X3] | LDR W7,[X6] ;
  STR W0,[X1] | MOV W5,#1   | LDR W8,[X1] ;
  MOV W2,#1   | STR W5,[X6] |             ;
  STR W2,[X3] |             |             ;
  exists (1:X4=1 /\ 2:X7=1 /\ 2:X8=0)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The Load instruction on P1, i.e. LDR W4,[X3], generates an Explicit Memory Read Effect of Location y;
  * The Store instruction on P1, i.e. STR W5,[X6], generates an Explicit Memory Write Effect of Location z with value 1;
  * The first Load instruction in program order on P2, i.e. LDR W7,[X6], generates an Explicit Memory Read Effect of Location z;
  * The second Load instruction in program order on P2, i.e. LDR W8,[X1], generates an Explicit Memory Read Effect of Location x;
  * The Register X4 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect on P1 Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STR W2,[X3];
  * The Register X7 on P2 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location z on P2 generated by LDR W7,[X6] Reads-from the Explicit Memory Write Effect on P1;
  * The Register X8 on P2 holds the value 0 in the end, which means that the Explicit Memory Read Effect of Location x on P2 generated by LDR W8,[X1] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1].
  
  == LB+addr+ctrl.litmus ==
  
  AArch64 LB+addr+ctrl
  "DpAddrdW Rfe DpCtrldW Rfe"
  Generator=diyone7 (version 7.58)
  Prefetch=0:x=F,0:y=W,1:y=F,1:x=W
  Com=Rf Rf
  Orig=DpAddrdW Rfe DpCtrldW Rfe
  {
  0:X0=x; 0:X4=y;
  1:X0=y; 1:X3=x;
  }
   P0                  | P1           ;
   LDR W1,[X0]         | LDR W1,[X0]  ;
   EOR W2,W1,W1        | CBNZ W1,LC00 ;
   MOV W3,#1           | LC00:        ;
   STR W3,[X4,W2,SXTW] | MOV W2,#1    ;
                       | STR W2,[X3]  ;
  exists (0:X1=1 /\ 1:X1=1)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The Load instruction on P0, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The Exclusive Or instruction on P0, i.e. EOR W2,W1,W1, creates an Address dependency from the Load instruction on P0, i.e. LDR W1,[X0], to the Store instruction on P0, i.e. STR W3,[X4,W2,SXTW];
  * The Store instruction on P0, i.e. STR W3,[X4,W2,SXTW], generates an Explicit Memory Write Effect of Location y with value 1;
  * The Load instruction on P1, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location y;
  * The Branch instruction on P1, i.e. CBNZ W1,LC00, creates a Control dependency from the Load instruction on P1, i.e. LDR W1,[X0], to the Store instruction on P1, i.e. STR W2,[X3];
  * The Store instruction on P1, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location x with value 1;
  * The Register X1 on P0 holds the value 1 in the end, which means that the Explicit Memory Read Effect on P0 Reads-from the Explicit Memory Write Effect on P1;
  * The Register X1 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect on P1 Reads-from the Explicit Memory Write Effect on P0.
  
  == LB.litmus ==
  
  AArch64 LB
  {
  0:X0=x; 0:X3=y;
  1:X0=x; 1:X3=y;
  }
   P0          | P1          ;
   LDR W1,[X0] | LDR W1,[X3] ;
   MOV W2,#1   | MOV W2,#1   ;
   STR W2,[X3] | STR W2,[X0] ;
  exists (0:X1=1 /\ 1:X1=1)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The Load instruction on P0, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The Store instruction on P0, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The Load instruction on P1, i.e. LDR W1,[X3], generates an Explicit Memory Read Effect of Location y;
  * The Store instruction on P1, i.e. STR W2,[X0], generates an Explicit Memory Write Effect of Location x with value 1;
  * The Register X1 on P0 holds the value 1 in the end, which means that the Explicit Memory Read Effect on P0 Reads-from the Explicit Memory Write Effect on P1;
  * The Register X1 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect on P1 Reads-from the Explicit Memory Write Effect on P0.
  
  == MP+poll+poaa-amo.casal-pola.litmus ==
  
  AArch64 MP+poll+poaa-amo.casal-pola
  "PodWWLL RfeLA PodRRAA Amo.CasAL PodWRLA FreAL"
  Generator=diyone7 (version 7.58)
  Prefetch=0:x=F,0:y=W,1:y=F,1:x=T
  Com=Rf Fr
  Orig=PodWWLL RfeLA PodRRAA Amo.CasAL PodWRLA FreAL
  {
  0:X1=x; 0:X3=y;
  1:X0=y; 1:X2=z; 1:X5=x;
  }
   P0           | P1               ;
   MOV W0,#1    | LDAR W1,[X0]     ;
   STLR W0,[X1] | MOV W3,#0        ;
   MOV W2,#1    | MOV W4,#1        ;
   STLR W2,[X3] | CASAL W3,W4,[X2] ;
                | LDAR W6,[X5]     ;
  exists (1:X1=1 /\ 1:X3=0 /\ 1:X6=0)
  
  This test asks whether one of the following candidate executions is architecturally Allowed:
  
  === First execution ===
  
  * The first Store Release instruction in program order on P0, i.e. STLR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store Release instruction in program order on P0, i.e. STLR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The first Load Acquire instruction in program order on P1, i.e. LDAR W1,[X0], generates an Explicit Memory Read Effect of Location y;
  * The CASAL instruction on P1, i.e. CASAL W3,W4,[X2], generates an Explicit Memory Read Effect of Location z;
  * The CASAL instruction on P1, i.e. CASAL W3,W4,[X2], generates an Explicit Memory Write Effect of Location z with value 1;
  * The second Load Acquire instruction in program order on P1, i.e. LDAR W6,[X5], generates an Explicit Memory Read Effect of Location x;
  * The Register X1 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location y on P1 generated by LDAR W1,[X0] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STLR W2,[X3];
  * The Register X3 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location z on P1 generated by CASAL W3,W4,[X2] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect on P1;
  * The Register X6 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDAR W6,[X5] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STLR W0,[X1].
  
  === Second execution ===
  
  * The first Store Release instruction in program order on P0, i.e. STLR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store Release instruction in program order on P0, i.e. STLR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The first Load Acquire instruction in program order on P1, i.e. LDAR W1,[X0], generates an Explicit Memory Read Effect of Location y;
  * The CASAL instruction on P1, i.e. CASAL W3,W4,[X2], generates an Explicit Memory Read Effect of Location z;
  * The CASAL instruction on P1, i.e. CASAL W3,W4,[X2], generates an Explicit Memory Write Effect of Location z with value 1;
  * The second Load Acquire instruction in program order on P1, i.e. LDAR W6,[X5], generates an Explicit Memory Read Effect of Location x;
  * The Register X1 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location y on P1 generated by LDAR W1,[X0] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STLR W2,[X3];
  * The Register X3 on P1 holds the value 0 in the end, because the Register Read Effect originating from the CASAL instruction on P1 has read the value 0 from the Register Write Effect originating from the MOV instruction on P1;
  * The Register X6 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDAR W6,[X5] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STLR W0,[X1].
  
  == MP.litmus ==
  
  AArch64 MP
  {
  0:X1=x; 0:X3=y;
  1:X1=x; 1:X3=y;
  }
   P0          | P1          ;
   MOV X0,#1   | LDR X4,[X3] ;
   STR X0,[X1] | LDR X6,[X1] ;
   MOV X2,#1   |             ;
   STR X2,[X3] |             ;
  exists (1:X4=1 /\ 1:X6=0)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The first Store instruction in program order on P0, i.e. STR X0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR X2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The first Load instruction in program order on P1, i.e. LDR X4,[X3], generates an Explicit Memory Read Effect of Location y;
  * The second Load instruction in program order on P1, i.e. LDR X6,[X1], generates an Explicit Memory Read Effect of Location x;
  * The Register X4 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location y on P1 generated by LDR X4,[X3] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STR X2,[X3];
  * The Register X6 on P1 holds the value 0 in the end, which means that the Explicit Memory Read Effect of Location x on P1 generated by LDR X6,[X1] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR X0,[X1].
  
  == PPOAA.litmus ==
  
  AArch64 PPOAA
  {
  0:X1=x; 0:X3=y;
  1:X3=y; 1:X5=z; 1:X1=x;
  }
  P0          | P1                  ;
  MOV W0,#1   | LDR W0,[X3]         ;
  STR W0,[X1] | EOR W2,W0,W0        ;
  MOV W2,#1   | MOV W4,#1           ;
  STR W2,[X3] | STR W4,[X5,W2,SXTW] ;
              | LDR W6,[X5]         ;
              | EOR W7,W6,W6        ;
              | LDR W8,[X1,W7,SXTW] ;
  exists (1:X0=1 /\ 1:X6=1 /\ 1:X8=0)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The first Load instruction in program order on P1, i.e. LDR W0,[X3], generates an Explicit Memory Read Effect of Location y;
  * The first Exclusive Or instruction in program order on P1, i.e. EOR W2,W0,W0, creates an Address dependency from the first Load instruction in program order on P1, i.e. LDR W0,[X3], to the Store instruction on P1, i.e. STR W4,[X5,W2,SXTW];
  * The Store instruction on P1, i.e. STR W4,[X5,W2,SXTW], generates an Explicit Memory Write Effect of Location z with value 1;
  * The second Load instruction in program order on P1, i.e. LDR W6,[X5], generates an Explicit Memory Read Effect of Location z;
  * The second Exclusive Or instruction in program order on P1, i.e. EOR W7,W6,W6, creates an Address dependency from the second Load instruction in program order on P1, i.e. LDR W6,[X5], to the third Load instruction in program order on P1, i.e. LDR W8,[X1,W7,SXTW];
  * The third Load instruction in program order on P1, i.e. LDR W8,[X1,W7,SXTW], generates an Explicit Memory Read Effect of Location x;
  * The Register X0 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location y on P1 generated by LDR W0,[X3] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STR W2,[X3];
  * The Register X6 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location z on P1 generated by LDR W6,[X5] Reads-from the Explicit Memory Write Effect on P1;
  * The Register X8 on P1 holds the value 0 in the end, which means that the Explicit Memory Read Effect of Location x on P1 generated by LDR W8,[X1,W7,SXTW] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1].
  
  == PPOAC.litmus ==
  
  AArch64 PPOAC
  {
  0:X1=x; 0:X3=y;
  1:X3=y; 1:X5=z; 1:X1=x;
  }
  P0          | P1                  ;
  MOV W0,#1   | LDR W0,[X3]         ;
  STR W0,[X1] | EOR W2,W0,W0        ;
  MOV W2,#1   | MOV W4,#1           ;
  STR W2,[X3] | STR W4,[X5,W2,SXTW] ;
              | LDR W6,[X5]         ;
              | CBNZ W6,LC00        ;
              | LC00:               ;
              | LDR W7,[X1]         ;
  exists (1:X0=1 /\ 1:X6=1 /\ 1:X7=0)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The first Load instruction in program order on P1, i.e. LDR W0,[X3], generates an Explicit Memory Read Effect of Location y;
  * The Exclusive Or instruction on P1, i.e. EOR W2,W0,W0, creates an Address dependency from the first Load instruction in program order on P1, i.e. LDR W0,[X3], to the Store instruction on P1, i.e. STR W4,[X5,W2,SXTW];
  * The Store instruction on P1, i.e. STR W4,[X5,W2,SXTW], generates an Explicit Memory Write Effect of Location z with value 1;
  * The second Load instruction in program order on P1, i.e. LDR W6,[X5], generates an Explicit Memory Read Effect of Location z;
  * The Branch instruction on P1, i.e. CBNZ W6,LC00, does not create any dependency to the third Load instruction in program order on P1, i.e. LDR W7,[X1];
  * The third Load instruction in program order on P1, i.e. LDR W7,[X1], generates an Explicit Memory Read Effect of Location x;
  * The Register X0 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location y on P1 generated by LDR W0,[X3] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STR W2,[X3];
  * The Register X6 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location z on P1 generated by LDR W6,[X5] Reads-from the Explicit Memory Write Effect on P1;
  * The Register X7 on P1 holds the value 0 in the end, which means that the Explicit Memory Read Effect of Location x on P1 generated by LDR W7,[X1] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1].
  
  == PPOCA.litmus ==
  
  AArch64 PPOCA
  {
  0:X1=x; 0:X3=y;
  1:X3=y; 1:X4=z; 1:X1=x;
  }
  P0          | P1                  ;
  MOV W0,#1   | LDR W0,[X3]         ;
  STR W0,[X1] | CBNZ W0,LC00        ;
  MOV W2,#1   | LC00:               ;
  STR W2,[X3] | MOV W2,#1           ;
              | STR W2,[X4]         ;
              | LDR W5,[X4]         ;
              | EOR W6,W5,W5        ;
              | LDR W7,[X1,W6,SXTW] ;
  exists (1:X0=1 /\ 1:X5=1 /\ 1:X7=0)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The first Load instruction in program order on P1, i.e. LDR W0,[X3], generates an Explicit Memory Read Effect of Location y;
  * The Branch instruction on P1, i.e. CBNZ W0,LC00, creates a Control dependency from the first Load instruction in program order on P1, i.e. LDR W0,[X3], to the Store instruction on P1, i.e. STR W2,[X4];
  * The Store instruction on P1, i.e. STR W2,[X4], generates an Explicit Memory Write Effect of Location z with value 1;
  * The second Load instruction in program order on P1, i.e. LDR W5,[X4], generates an Explicit Memory Read Effect of Location z;
  * The Exclusive Or instruction on P1, i.e. EOR W6,W5,W5, creates an Address dependency from the second Load instruction in program order on P1, i.e. LDR W5,[X4], to the third Load instruction in program order on P1, i.e. LDR W7,[X1,W6,SXTW];
  * The third Load instruction in program order on P1, i.e. LDR W7,[X1,W6,SXTW], generates an Explicit Memory Read Effect of Location x;
  * The Register X0 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location y on P1 generated by LDR W0,[X3] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STR W2,[X3];
  * The Register X5 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location z on P1 generated by LDR W5,[X4] Reads-from the Explicit Memory Write Effect on P1;
  * The Register X7 on P1 holds the value 0 in the end, which means that the Explicit Memory Read Effect of Location x on P1 generated by LDR W7,[X1,W6,SXTW] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1].
  
  == PPOCC.litmus ==
  
  AArch64 PPOCC
  {
  0:X1=x; 0:X3=y;
  1:X3=y; 1:X4=z; 1:X1=x;
  }
  P0 | P1 ;
  MOV W0,#1   | LDR W0,[X3]  ;
  STR W0,[X1] | CBNZ W0,LC00 ;
  MOV W2,#1   | LC00:        ;
  STR W2,[X3] | MOV W2,#1    ;
              | STR W2,[X4]  ;
              | LDR W5,[X4]  ;
              | CBNZ W5,LC01 ;
              | LC01:        ;
              | LDR W6,[X1]  ;
  exists (1:X0=1 /\ 1:X5=1 /\ 1:X6=0)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The first Load instruction in program order on P1, i.e. LDR W0,[X3], generates an Explicit Memory Read Effect of Location y;
  * The first Branch instruction in program order on P1, i.e. CBNZ W0,LC00, creates a Control dependency from the first Load instruction in program order on P1, i.e. LDR W0,[X3], to the Store instruction on P1, i.e. STR W2,[X4];
  * The Store instruction on P1, i.e. STR W2,[X4], generates an Explicit Memory Write Effect of Location z with value 1;
  * The second Load instruction in program order on P1, i.e. LDR W5,[X4], generates an Explicit Memory Read Effect of Location z;
  * The second Branch instruction in program order on P1, i.e. CBNZ W5,LC01, does not create any dependency to the third Load instruction in program order on P1, i.e. LDR W6,[X1];
  * The third Load instruction in program order on P1, i.e. LDR W6,[X1], generates an Explicit Memory Read Effect of Location x;
  * The Register X0 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location y on P1 generated by LDR W0,[X3] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STR W2,[X3];
  * The Register X5 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location z on P1 generated by LDR W5,[X4] Reads-from the Explicit Memory Write Effect on P1;
  * The Register X6 on P1 holds the value 0 in the end, which means that the Explicit Memory Read Effect of Location x on P1 generated by LDR W6,[X1] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1].
  
  == PPODA.litmus ==
  
  AArch64 PPODA
  {
  0:X1=x; 0:X3=y;
  1:X3=y; 1:X4=z; 1:X1=x;
  }
  P0          | P1                  ;
  MOV W0,#1   | LDR W0,[X3]         ;
  STR W0,[X1] | EOR W2,W0,W0        ;
  MOV W2,#1   | ADD W2,W2,#1        ;
  STR W2,[X3] | STR W2,[X4]         ;
              | LDR W5,[X4]         ;
              | EOR W6,W5,W5        ;
              | LDR W7,[X1,W6,SXTW] ;
  exists (1:X0=1 /\ 1:X5=1 /\ 1:X7=0)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The first Load instruction in program order on P1, i.e. LDR W0,[X3], generates an Explicit Memory Read Effect of Location y;
  * The first Exclusive Or instruction in program order on P1, i.e. EOR W2,W0,W0, and the Add instruction on P1, i.e. ADD W2,W2,#1, create a Data dependency from the first Load instruction in program order on P1, i.e. LDR W0,[X3], to the Store instruction on P1, i.e. STR W2,[X4];
  * The Store instruction on P1, i.e. STR W2,[X4], generates an Explicit Memory Write Effect of Location z with value 1;
  * The second Load instruction in program order on P1, i.e. LDR W5,[X4], generates an Explicit Memory Read Effect of Location z;
  * The second Exclusive Or instruction in program order on P1, i.e. EOR W6,W5,W5, creates an Address dependency from the second Load instruction in program order on P1, i.e. LDR W5,[X4], to the third Load instruction in program order on P1, i.e. LDR W7,[X1,W6,SXTW];
  * The third Load instruction in program order on P1, i.e. LDR W7,[X1,W6,SXTW], generates an Explicit Memory Read Effect of Location x;
  * The Register X0 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location y on P1 generated by LDR W0,[X3] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STR W2,[X3];
  * The Register X5 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location z on P1 generated by LDR W5,[X4] Reads-from the Explicit Memory Write Effect on P1;
  * The Register X7 on P1 holds the value 0 in the end, which means that the Explicit Memory Read Effect of Location x on P1 generated by LDR W7,[X1,W6,SXTW] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1].
  
  == PPODC.litmus ==
  
  AArch64 PPODC
  {
  0:X1=x; 0:X3=y;
  1:X3=y; 1:X4=z; 1:X1=x;
  }
  P0          | P1           ;
  MOV W0,#1   | LDR W0,[X3]  ;
  STR W0,[X1] | EOR W2,W0,W0 ;
  MOV W2,#1   | ADD W2,W2,#1 ;
  STR W2,[X3] | STR W2,[X4]  ;
              | LDR W5,[X4]  ;
              | CBNZ W5,LC00 ;
              | LC00:        ;
              | LDR W6,[X1]  ;
  exists (1:X0=1 /\ 1:X5=1 /\ 1:X6=0)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The first Load instruction in program order on P1, i.e. LDR W0,[X3], generates an Explicit Memory Read Effect of Location y;
  * The Exclusive Or instruction on P1, i.e. EOR W2,W0,W0, and the Add instruction on P1, i.e. ADD W2,W2,#1, create a Data dependency from the first Load instruction in program order on P1, i.e. LDR W0,[X3], to the Store instruction on P1, i.e. STR W2,[X4];
  * The Store instruction on P1, i.e. STR W2,[X4], generates an Explicit Memory Write Effect of Location z with value 1;
  * The second Load instruction in program order on P1, i.e. LDR W5,[X4], generates an Explicit Memory Read Effect of Location z;
  * The Branch instruction on P1, i.e. CBNZ W5,LC00, does not create any dependency to the third Load instruction in program order on P1, i.e. LDR W6,[X1];
  * The third Load instruction in program order on P1, i.e. LDR W6,[X1], generates an Explicit Memory Read Effect of Location x;
  * The Register X0 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location y on P1 generated by LDR W0,[X3] Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STR W2,[X3];
  * The Register X5 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location z on P1 generated by LDR W5,[X4] Reads-from the Explicit Memory Write Effect on P1;
  * The Register X6 on P1 holds the value 0 in the end, which means that the Explicit Memory Read Effect of Location x on P1 generated by LDR W6,[X1] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1].
  
  == R+WR+W+RW.litmus ==
  
  AArch64 R+WR+W+RW
  {
  0:X1=x;
  1:X1=x; 1:X2=y;
  2:X2=y;
  3:X2=y; 3:X1=x;
  }
  P0          | P1          | P2          | P3          ;
  LDR W3,[X1] | MOV W0,#2   | MOV W0,#1   | LDR W4,[X2] ;
              | STR W0,[X1] | STR W0,[X2] | MOV W5,#1   ;
              | LDR W3,[X2] |             | STR W5,[X1] ;
  exists ([x]=2 /\ 0:X3=1 /\ 1:X3=0 /\ 3:X4=1)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The Load instruction on P0, i.e. LDR W3,[X1], generates an Explicit Memory Read Effect of Location x;
  * The Store instruction on P1, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 2;
  * The Load instruction on P1, i.e. LDR W3,[X2], generates an Explicit Memory Read Effect of Location y;
  * The Store instruction on P2, i.e. STR W0,[X2], generates an Explicit Memory Write Effect of Location y with value 1;
  * The Load instruction on P3, i.e. LDR W4,[X2], generates an Explicit Memory Read Effect of Location y;
  * The Store instruction on P3, i.e. STR W5,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The value of x is 2 in the end, which means that the Explicit Memory Write Effect on P3 is Coherence-before the Explicit Memory Write Effect on P1;
  * The Register X3 on P0 holds the value 1 in the end, which means that the Explicit Memory Read Effect on P0 Reads-from the Explicit Memory Write Effect on P3;
  * The Register X3 on P1 holds the value 0 in the end, which means that the Explicit Memory Read Effect on P1 Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect on P2;
  * The Register X4 on P3 holds the value 1 in the end, which means that the Explicit Memory Read Effect on P3 Reads-from the Explicit Memory Write Effect on P2.
  
  == R+WW+RW.litmus ==
  
  AArch64 R+WW+RW
  {
  0:X1=x;
  1:X1=x; 1:X3=y;
  2:X3=y; 2:X1=x;
  }
  P0          | P1          | P2          ;
  LDR W6,[X1] | MOV W0,#2   | LDR W4,[X3] ;
              | STR W0,[X1] | MOV W5,#1   ;
              | MOV W2,#1   | STR W5,[X1] ;
              | STR W2,[X3] |             ;
  exists ([x]=2 /\ 0:X6=1 /\ 2:X4=1)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The Load instruction on P0, i.e. LDR W6,[X1], generates an Explicit Memory Read Effect of Location x;
  * The first Store instruction in program order on P1, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 2;
  * The second Store instruction in program order on P1, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The Load instruction on P2, i.e. LDR W4,[X3], generates an Explicit Memory Read Effect of Location y;
  * The Store instruction on P2, i.e. STR W5,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The value of x is 2 in the end, which means that the Explicit Memory Write Effect on P2 is Coherence-before the Explicit Memory Write Effect of Location x on P1 generated by STR W0,[X1];
  * The Register X6 on P0 holds the value 1 in the end, which means that the Explicit Memory Read Effect on P0 Reads-from the Explicit Memory Write Effect on P2;
  * The Register X4 on P2 holds the value 1 in the end, which means that the Explicit Memory Read Effect on P2 Reads-from the Explicit Memory Write Effect of Location y on P1 generated by STR W2,[X3].
  
  == W+RR+WR+WR.litmus ==
  
  AArch64 W+RR+WR+WR
  {
  0:X1=x;
  1:X1=x; 1:X2=y;
  2:X2=y; 2:X5=z;
  3:X5=z; 3:X1=x;
  }
  P0          | P1          | P2          | P3          ;
  MOV W0,#1   | LDR W4,[X1] | MOV W0,#1   | MOV W0,#1   ;
  STR W0,[X1] | LDR W3,[X2] | STR W0,[X2] | STR W0,[X5] ;
              |             | LDR W3,[X5] | LDR W3,[X1] ;
  exists (1:X4=1 /\ 1:X3=0 /\ 2:X3=0 /\ 3:X3=0 /\ y=1 /\ z=1)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The Store instruction on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The first Load instruction in program order on P1, i.e. LDR W4,[X1], generates an Explicit Memory Read Effect of Location x;
  * The second Load instruction in program order on P1, i.e. LDR W3,[X2], generates an Explicit Memory Read Effect of Location y;
  * The Store instruction on P2, i.e. STR W0,[X2], generates an Explicit Memory Write Effect of Location y with value 1;
  * The Load instruction on P2, i.e. LDR W3,[X5], generates an Explicit Memory Read Effect of Location z;
  * The Store instruction on P3, i.e. STR W0,[X5], generates an Explicit Memory Write Effect of Location z with value 1;
  * The Load instruction on P3, i.e. LDR W3,[X1], generates an Explicit Memory Read Effect of Location x;
  * The Register X4 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location x on P1 generated by LDR W4,[X1] Reads-from the Explicit Memory Write Effect on P0;
  * The Register X3 on P1 holds the value 0 in the end, which means that the Explicit Memory Read Effect of Location y on P1 generated by LDR W3,[X2] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect on P2;
  * The Register X3 on P2 holds the value 0 in the end, which means that the Explicit Memory Read Effect on P2 Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect on P3;
  * The Register X3 on P3 holds the value 0 in the end, which means that the Explicit Memory Read Effect on P3 Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect on P0;
  * The value of y is 1 in the end, which means that the Store instruction on P2 has updated the memory;
  * The value of z is 1 in the end, which means that the Store instruction on P3 has updated the memory.
  
  == W+RW+R+WR.litmus ==
  
  AArch64 W+RW+R+WR
  "Rfe PodRW Rfe Fre PodWR Fre"
  Generator=diyone7 (version 7.58)
  Prefetch=1:x=F,1:y=W,3:y=F,3:x=T
  Com=Rf Rf Fr Fr
  Orig=Rfe PodRW Rfe Fre PodWR Fre
  {
  0:X1=x;
  1:X0=x; 1:X3=y;
  2:X0=y;
  3:X1=y; 3:X2=x;
  }
   P0          | P1          | P2          | P3          ;
   MOV W0,#1   | LDR W1,[X0] | LDR W1,[X0] | MOV W0,#2   ;
   STR W0,[X1] | MOV W2,#1   |             | STR W0,[X1] ;
               | STR W2,[X3] |             | LDR W3,[X2] ;
  exists ([y]=2 /\ 1:X1=1 /\ 2:X1=1 /\ 3:X3=0)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The Store instruction on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The Load instruction on P1, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The Store instruction on P1, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The Load instruction on P2, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location y;
  * The Store instruction on P3, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location y with value 2;
  * The Load instruction on P3, i.e. LDR W3,[X2], generates an Explicit Memory Read Effect of Location x;
  * The value of y is 2 in the end, which means that the Explicit Memory Write Effect on P1 is Coherence-before the Explicit Memory Write Effect on P3;
  * The Register X1 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect on P1 Reads-from the Explicit Memory Write Effect on P0;
  * The Register X1 on P2 holds the value 1 in the end, which means that the Explicit Memory Read Effect on P2 Reads-from the Explicit Memory Write Effect on P1;
  * The Register X3 on P3 holds the value 0 in the end, which means that the Explicit Memory Read Effect on P3 Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect on P0.
  
  == WRC.litmus ==
  
  AArch64 WRC
  {
  0:X0=x;
  1:X0=x; 1:X3=y;
  2:X0=x; 2:X3=y;
  }
  P0          | P1          | P2          ;
  MOV W1,#1   | LDR W1,[X0] | LDR W1,[X3] ;
  STR W1,[X0] | MOV W2,#1   | LDR W4,[X0] ;
              | STR W2,[X3] |             ;
  exists (1:X1=1 /\ 2:X1=1 /\ 2:X4=0)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The Store instruction on P0, i.e. STR W1,[X0], generates an Explicit Memory Write Effect of Location x with value 1;
  * The Load instruction on P1, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The Store instruction on P1, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The first Load instruction in program order on P2, i.e. LDR W1,[X3], generates an Explicit Memory Read Effect of Location y;
  * The second Load instruction in program order on P2, i.e. LDR W4,[X0], generates an Explicit Memory Read Effect of Location x;
  * The Register X1 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect on P1 Reads-from the Explicit Memory Write Effect on P0;
  * The Register X1 on P2 holds the value 1 in the end, which means that the Explicit Memory Read Effect of Location y on P2 generated by LDR W1,[X3] Reads-from the Explicit Memory Write Effect on P1;
  * The Register X4 on P2 holds the value 0 in the end, which means that the Explicit Memory Read Effect of Location x on P2 generated by LDR W4,[X0] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect on P0.
  
  == WW+RW+R.litmus ==
  
  AArch64 WW+RW+R
  "PodWW Rfe PodRW Rfe Fre"
  Generator=diyone7 (version 7.58)
  Prefetch=0:x=F,0:y=W,1:y=F,1:x=W
  Com=Rf Rf Fr
  Orig=PodWW Rfe PodRW Rfe Fre
  {
  0:X1=x; 0:X3=y;
  1:X0=y; 1:X3=x;
  2:X0=x;
  }
   P0          | P1          | P2          ;
   MOV W0,#2   | LDR W1,[X0] | LDR W1,[X0] ;
   STR W0,[X1] | MOV W2,#1   |             ;
   MOV W2,#1   | STR W2,[X3] |             ;
   STR W2,[X3] |             |             ;
  exists ([x]=2 /\ 1:X1=1 /\ 2:X1=1)
  
  This test asks whether the following execution is architecturally Allowed:
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 2;
  * The second Store instruction in program order on P0, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location y with value 1;
  * The Load instruction on P1, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location y;
  * The Store instruction on P1, i.e. STR W2,[X3], generates an Explicit Memory Write Effect of Location x with value 1;
  * The Load instruction on P2, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The value of x is 2 in the end, which means that the Explicit Memory Write Effect on P1 is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1];
  * The Register X1 on P1 holds the value 1 in the end, which means that the Explicit Memory Read Effect on P1 Reads-from the Explicit Memory Write Effect of Location y on P0 generated by STR W2,[X3];
  * The Register X1 on P2 holds the value 1 in the end, which means that the Explicit Memory Read Effect on P2 Reads-from the Explicit Memory Write Effect on P1.
  
  == multi_execs.litmus ==
  
  AArch64 multi_execs
  "PosWW PosWW Rfe PosRR Fre"
  Generator=diyone7 (version 7.58)
  Com=Rf Fr
  Orig=PosWW PosWW Rfe PosRR Fre
  {
  0:X1=x;
  1:X0=x;
  }
   P0          | P1          ;
   MOV W0,#1   | LDR W1,[X0] ;
   STR W0,[X1] | LDR W2,[X0] ;
   MOV W2,#1   | LDR W3,[X0] ;
   STR W2,[X1] |             ;
   MOV W3,#3   |             ;
   STR W3,[X1] |             ;
  exists ([x]=3 /\ 1:X1=3 /\ 1:X2=1 /\ 1:X3=0)
  
  This test asks whether one of the following candidate executions is architecturally Allowed:
  
  === First execution ===
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The third Store instruction in program order on P0, i.e. STR W3,[X1], generates an Explicit Memory Write Effect of Location x with value 3;
  * The first Load instruction in program order on P1, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The second Load instruction in program order on P1, i.e. LDR W2,[X0], generates an Explicit Memory Read Effect of Location x;
  * The third Load instruction in program order on P1, i.e. LDR W3,[X0], generates an Explicit Memory Read Effect of Location x;
  * The value of x is 3 in the end, because the Explicit Memory Write Effect of Location x on P0 generated by STR W2,[X1] is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X1 on P1 holds the value 3 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W1,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X2 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W2,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1];
  * The Register X3 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W3,[X0] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1].
  
  === Second execution ===
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The third Store instruction in program order on P0, i.e. STR W3,[X1], generates an Explicit Memory Write Effect of Location x with value 3;
  * The first Load instruction in program order on P1, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The second Load instruction in program order on P1, i.e. LDR W2,[X0], generates an Explicit Memory Read Effect of Location x;
  * The third Load instruction in program order on P1, i.e. LDR W3,[X0], generates an Explicit Memory Read Effect of Location x;
  * The value of x is 3 in the end, because the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1] is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X1 on P1 holds the value 3 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W1,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X2 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W2,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1];
  * The Register X3 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W3,[X0] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W2,[X1].
  
  === Third execution ===
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The third Store instruction in program order on P0, i.e. STR W3,[X1], generates an Explicit Memory Write Effect of Location x with value 3;
  * The first Load instruction in program order on P1, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The second Load instruction in program order on P1, i.e. LDR W2,[X0], generates an Explicit Memory Read Effect of Location x;
  * The third Load instruction in program order on P1, i.e. LDR W3,[X0], generates an Explicit Memory Read Effect of Location x;
  * The value of x is 3 in the end, because the Explicit Memory Write Effect of Location x on P0 generated by STR W2,[X1] is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X1 on P1 holds the value 3 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W1,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X2 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W2,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W2,[X1];
  * The Register X3 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W3,[X0] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1].
  
  === Fourth execution ===
  
  * The first Store instruction in program order on P0, i.e. STR W0,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The second Store instruction in program order on P0, i.e. STR W2,[X1], generates an Explicit Memory Write Effect of Location x with value 1;
  * The third Store instruction in program order on P0, i.e. STR W3,[X1], generates an Explicit Memory Write Effect of Location x with value 3;
  * The first Load instruction in program order on P1, i.e. LDR W1,[X0], generates an Explicit Memory Read Effect of Location x;
  * The second Load instruction in program order on P1, i.e. LDR W2,[X0], generates an Explicit Memory Read Effect of Location x;
  * The third Load instruction in program order on P1, i.e. LDR W3,[X0], generates an Explicit Memory Read Effect of Location x;
  * The value of x is 3 in the end, because the Explicit Memory Write Effect of Location x on P0 generated by STR W0,[X1] is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X1 on P1 holds the value 3 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W1,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W3,[X1];
  * The Register X2 on P1 holds the value 1 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W2,[X0] Reads-from the Explicit Memory Write Effect of Location x on P0 generated by STR W2,[X1];
  * The Register X3 on P1 holds the value 0 in the end, because the Explicit Memory Read Effect of Location x on P1 generated by LDR W3,[X0] Reads-from the initial state, and therefore is Coherence-before the Explicit Memory Write Effect of Location x on P0 generated by STR W2,[X1].
  
