Force test timeouts by picking an expensive test and setting the timeout to a
single millisecondand observe the timeout is applied for every litmus test

  $ herd7 -set-libdir ../libdir -timeout 0.001 Armv8-ext-forbidden000018.litmus Armv8-ext-forbidden000018.litmus Armv8-ext-forbidden000018.litmus
  Warning: File "Armv8-ext-forbidden000018.litmus": timed out
  Warning: File "Armv8-ext-forbidden000018.litmus": timed out
  Warning: File "Armv8-ext-forbidden000018.litmus": timed out
  [154]

Note that 154 is generated by adding SIGVTALRM 26, and 128, because the
execution got interrupted by a signal.
