record = "AArch64"

cats = [
    "cats/aarch64.cat",
    "cats/aarch64-MTE.cat",
    ]

cfgs = [
    "cfgs/web-MTE.cfg",
]

illustrative_tests = [
    "tests/coWR-mte.litmus",
    "tests/MP+dmb.stPT+addr.litmus",
    "tests/MP+dmb.stTT+addr.litmus",
    "tests/S+dmb.stTT+addr.litmus",
    "tests/S+dmb.stTT+ctrl.litmus",
    "tests/S+dmb.stTT+data.litmus",
    "tests/S+dmb.stTT+rel.litmus",
    "tests/LDR-STZG1.litmus",
    "tests/LDR-STZG2.litmus",
    "tests/Wt+RtWtRt.litmus",
    "tests/RtWtRt+WztWzt.litmus",
    "tests/MTE-CoRR+addr+READS.litmus",
    "tests/MTE-CoRR+dmb.ld+READS.litmus",
    "tests/MTE-CoRR+READ+FAULT.litmus",
    "tests/MTE-CoRR+READS.litmus",
    "tests/MTE-CoRW1+FAULT.litmus",
    "tests/MTE-CoRW1+READ.litmus",
    "tests/MTE-CoRW2+FAULT.litmus",
    "tests/MTE-CoRW2+READ.litmus",
    "tests/MTE-CoWR+FAULT.litmus",
    "tests/MTE-CoWR+READ.litmus",
    "tests/MTE-CoWW.litmus",
    "tests/MTE-LDRLDR.litmus",
    "tests/MTE-LDRSTGLDR.litmus",
    "tests/MTE-RFI.litmus",
    "tests/MTE-RW+WR+amo.ldeoral-polp+dmb.sytq.litmus",
    "tests/coRR-RTW.litmus",
    "tests/coRR-T+RR.litmus",
    "tests/coRR-T+RT.litmus",
    "tests/coRR-T+RW.litmus",
    "tests/coRR-T+TR.litmus",
    "tests/coRR-T+TW.litmus",
    "tests/coRR-T+WR.litmus",
    "tests/coRR-T+WT.litmus",
    "tests/coRR-T+WW.litmus",
    "tests/coRR-TR.litmus",
    "tests/coRR-TRTW.litmus",
    "tests/coRR-TT.litmus",
    "tests/coRR-TW.litmus",
    "tests/coRR-TWTR.litmus",
    "tests/coRR-WTW.litmus",
    "tests/coRTW.litmus",
    "tests/coTR.litmus",
    "tests/coTRTW.litmus",
    "tests/coTW.litmus",
    "tests/coTWTR.litmus",
    "tests/coTWTW.litmus",
    "tests/coWTW.litmus",
]
