record = "AArch64 Down-One-Leg"

cats = [
    "cats/aarch64-dol.cat",
]

cfgs = [
    "cfgs/web-dol.cfg",
]

illustrative_tests = [
    "tests/2+2W+addr+dmb.litmus",
    "tests/2+2W+xp+dmb.litmus",
    "tests/H10X.litmus",
    "tests/H10bX.litmus",
    "tests/H11V.litmus",
    "tests/H11bQ.litmus",
    "tests/H12CV.litmus",
    "tests/H12V.litmus",
    "tests/H13V.litmus",
    "tests/H14V.litmus",
    "tests/H15V.litmus",
    "tests/H16X.litmus",
    "tests/H1CX.litmus",
    "tests/H1X.litmus",
    "tests/H2CV.litmus",
    "tests/H2V.litmus",
    "tests/H3CV.litmus",
    "tests/H3V.litmus",
    "tests/H3bCQ.litmus",
    "tests/H3bQ.litmus",
    "tests/H4CX.litmus",
    "tests/H4X.litmus",
    "tests/H5CV.litmus",
    "tests/H5V.litmus",
    "tests/H6CX.litmus",
    "tests/H6X.litmus",
    "tests/H7CX.litmus",
    "tests/H7X.litmus",
    "tests/H8CX.litmus",
    "tests/H8X.litmus",
    "tests/H8bCQ.litmus",
    "tests/H8bQ.litmus",
    "tests/H8cQ.litmus",
    "tests/H9CV.litmus",
    "tests/H9V.litmus",
    "tests/LB6b.litmus",
    "tests/LB6b2.litmus",
    "tests/LB6b3.litmus",
#    "tests/MP-STXR.litmus",
#    "tests/MP-STXR-fail.litmus",
#    "tests/MP-STXR-success.litmus",
    "tests/MP+DMB.ST+B.litmus",
    "tests/MP+DMB.ST+B-EOR.litmus",
    "tests/MP+DMB.ST+CSEL.litmus",
#    "tests/PPCOA4b.litmus",
    "tests/PPOCA.litmus",
    "tests/PPOCA5b.litmus",
    "tests/PPOCA6b.litmus",
#    "tests/S-STXR-success.litmus",
    "tests/STXR-ctrl.litmus",
    "tests/STXR-ctrl1.litmus",
    "tests/STXR-ctrl1a.litmus",
    "tests/STXR-ctrl1b.litmus",
    "tests/STXR-ctrl2.litmus",
    "tests/STXR-ctrl3.litmus",
    "tests/STXR-ctrla.litmus",
    "tests/SpecCE-01.litmus",
    "tests/SpecCE-02.litmus",
    "tests/SpecCE-03.litmus",
    "tests/SpecCE-04.litmus",
    "tests/SpecCE-05.litmus",
    "tests/SpecCoiV.litmus",
    "tests/SpecCoiX.litmus",
    "tests/SpecRfeX.litmus",
    "tests/SpecRfiV.litmus",
    "tests/SpecRfiX.litmus",
]
