(executable
 (name gen))

(executable
 (name asltest)
 (optional)
 (libraries yaml yojson jsonschema))

(subdir
 run
 (dynamic_include ../generate/dune.inc))

(subdir
 generate
 (rule
  (deps
   (glob_files_rec ../tests/*.asl)
   (glob_files_rec ../tests/*.yaml))
  (action
   (with-stdout-to
    dune.inc
    (run ../gen.exe)))))
