


export ACL2_IMAGES=$(CURDIR)/bin
export ACL2_IMAGE_SRC_DIR=$(CURDIR)/image-src
export ACL2_PROJECTS=$(CURDIR)/PROJECT_DIRS

all : bin/acl2asl

bin :
	mkdir bin

bin/acl2asl : bin
	cert.pl -g acl2asl

