record = "Concurrency Readers' Guide"

cats = [
    "cats/aarch64.cat",
    "cats/sc.cat",
]

cfgs = [
    "cfgs/new-web.cfg",
]

illustrative_tests = [
    "tests/2+2w.litmus",
    "tests/coRR-pte9-mod.litmus",
    "tests/CoRR.litmus",
    "tests/CoRW1-Exp.litmus",
    "tests/coRW1.litmus",
    "tests/coRW2.litmus",
    "tests/CoWR-Exp.litmus",
    "tests/coWR.litmus",
    "tests/CoWW-Exp.litmus",
    "tests/coWW.litmus",
    "tests/DIC1.MP.FF+dmb.st+po.litmus",
    "tests/IRIW.litmus",
    "tests/IRIW+dmb.lds.litmus",
    "tests/ISA2.litmus",
    "tests/LB.litmus",
    "tests/Marc03.litmus",
    "tests/miniMarc03.litmus",
    "tests/MP.FF+dc.cvau-dsb.ish-ic.ivau-dsb.ish+po.litmus",
    "tests/MP.litmus",
    "tests/MP.V2I+dsb.ish-tlbi.vaae1is-dsh.ish+dsb.ish-isb.litmus",
    "tests/MP+dmb.st+LDIAPP.litmus",
    "tests/MP+rel+acq.litmus",
    "tests/MP+STILP+dmb.ld.litmus",
    "tests/PPOAA.litmus",
    "tests/PPOAC.litmus",
    "tests/PPOCA-catalogue.litmus",
    "tests/PPOCA.litmus",
    "tests/PPOCC.litmus",
    "tests/PPODA.litmus",
    "tests/PPODC.litmus",
    "tests/R.litmus",
    "tests/R+WR+W+RW.litmus",
    "tests/R+WW+RW.litmus",
    "tests/RDW.litmus",
    "tests/rmw-cas.litmus",
    "tests/rmw-ldxr-stxr.litmus",
    "tests/RSW.litmus",
    "tests/RWC.litmus",
    "tests/S.litmus",
    "tests/SB.litmus",
    "tests/SB+rfi-dmb.ld+rfi-dmb.ld.litmus",
    "tests/W+RR+2W.litmus",
    "tests/W+RR+WR+WR.litmus",
    "tests/W+RR+WR+WW.litmus",
    "tests/W+RW+2W.litmus",
    "tests/W+RW+RR.litmus",
    "tests/W+RW+W+RW.litmus",
    "tests/W+RW+WR.litmus",
    "tests/W+WR+RR+W.litmus",
    "tests/WRC.litmus",
    "tests/WRC+rel+addr.litmus",
    "tests/WWC.litmus",
    "tests/Z6.3.litmus",
]
