record = "linux"

cats = [
    "cats/linux-kernel.cat"
    ]

cfgs = [
    "cfgs/linux-kernel.cfg"
]

bells = [
    "cats/linux-kernel.bell"
]

illustrative_tests = [
    "tests/MP+relacq.litmus",
    "tests/add_unless_mb.litmus",
    "tests/dep+plain.litmus",
    "tests/C-2+2W+o-o+o-o.litmus",
    "tests/C-2+2W+o-wmb-o+o-wmb-o.litmus",
    "tests/C-CCIRIW+o+o+o-o+o-o.litmus",
    "tests/C-cmpxchg.litmus",
    "tests/C-ISA2+o-r+a-r+a-r+a-o.litmus",
    "tests/C-LB+a-o+o-data-o+o-data-o.litmus",
    "tests/C-LB+a-r+a-r+a-r+a-r.litmus",
    "tests/C-LB+cmpxchg-ctrl-o+o-ctrl-o.litmus",
    "tests/C-LB+o-cge-o+o-cge-o+dstb.litmus",
    "tests/C-LB+o-cge-o+o-cge-o.litmus",
    "tests/C-LB+o-cgt-o+o-cgt-o.litmus",
    "tests/C-LB+o-data-o+o-data-o+o-data-o.litmus",
    "tests/C-LB+o-o+o-o.litmus",
    "tests/C-LB+o-r+a-o.litmus",
    "tests/C-LB+o-r+o-ctrl-o.litmus",
    "tests/C-LB+o-r+o-data-o.litmus",
    "tests/C-MP-OMCA+o-o-o+o-rmb-o.litmus",
    "tests/C-MP+o-o+o-rmb-o.litmus",
    "tests/C-MP+o-r+o-ctrl-o.litmus",
    "tests/C-MP+o-wmb-o+o-addr-o.litmus",
    "tests/C-MP+o-wmb-o+o-o.litmus",
    "tests/C-MP+o-wmb-o+o-rmb-o.litmus",
    "tests/CoRR+poonceonce+Once.litmus",
    "tests/CoRW+poonceonce+Once.litmus",
    "tests/CoWR+poonceonce+Once.litmus",
    "tests/CoWW+poonceonce.litmus",
    "tests/C-RomanPenyaev-list-rcu-rr.litmus",
    "tests/C-R+o-wmb-o+o-mb-o.litmus",
    "tests/C-SB+o-mb-o+o-mb-o.litmus",
    "tests/C-SB-OMCA+o-o-rmb-o+o-o-rmb-o.litmus",
    "tests/C-SB+o-o+o-o.litmus",
    "tests/C-S+o-wmb-o+o-addr-o.litmus",
    "tests/C-WRC+o+o-data-o+o-rmb-o.litmus",
    "tests/C-WRC+o+o-r+a-o.litmus",
    "tests/C-W+RWC+o-mb-o+a-o+o-mb-o.litmus",
    "tests/C-W+RWC+o-r+a-o+o-mb-o.litmus",
    "tests/C-WWC+o-cge-o+o-cge-o+o+dstb.litmus",
    "tests/C-WWC+o-cge-o+o-cge-o+o.litmus",
    "tests/C-WWC+o-cgt-o+o-cgt-o+o+dstb.litmus",
    "tests/C-WWC+o-cgt-o+o-cgt-o+o.litmus",
    "tests/C-WWC+o+o-data-o+o-addr-o.litmus",
    "tests/C-WWC+o+o-r+o-addr-o.litmus",
    "tests/C-Z6.2+o-r+a-o+o-mb-o.litmus",
    "tests/C-Z6.2+o-r+a-r+a-r+a-o.litmus",
    "tests/IRIW+fencembonceonces+OnceOnce.litmus",
    "tests/IRIW+poonceonces+OnceOnce.litmus",
    "tests/ISA2+pooncelock+pooncelock+pombonce.litmus",
    "tests/ISA2+poonceonces.litmus",
    "tests/ISA2+pooncerelease+poacquirerelease+poacquireonce.litmus",
    "tests/LB+fencembonceonce+ctrlonceonce.litmus",
    "tests/LB+poacquireonce+pooncerelease.litmus",
    "tests/LB+poonceonces.litmus",
    "tests/LB+unlocklockonceonce+poacquireonce.litmus",
    "tests/Lock-outside-across.litmus",
    "tests/MP+fencewmbonceonce+fencermbonceonce.litmus",
    "tests/MP+onceassign+derefonce.litmus",
    "tests/MP+polockmbonce+poacquiresilsil.litmus",
    "tests/MP+polockonce+poacquiresilsil.litmus",
    "tests/MP+polocks.litmus",
    "tests/MP+poonceonces.litmus",
    "tests/MP+pooncerelease+poacquireonce.litmus",
    "tests/MP+porevlocks.litmus",
    "tests/MP+unlocklockonceonce+fencermbonceonce.litmus",
    "tests/R+fencembonceonces.litmus",
    "tests/R+poonceonces.litmus",
    "tests/SB+fencembonceonces.litmus",
    "tests/SB+poonceonces.litmus",
    "tests/SB+rfionceonce-poonceonces.litmus",
    "tests/S+fencewmbonceonce+poacquireonce.litmus",
    "tests/spinlock-is-locked-self.litmus",
    "tests/S+poonceonces.litmus",
    "tests/WRC+poonceonces+Once.litmus",
    "tests/WRC+pooncerelease+fencermbonceonce+Once.litmus",
    "tests/Z6.0+pooncelock+pooncelock+pombonce.litmus",
    "tests/Z6.0+pooncelock+pooncelock-mb+pombonce.litmus",
    "tests/Z6.0+pooncerelease+poacquirerelease+fencembonceonce.litmus",
]
