(****************************************************************************)
(*                           the diy toolsuite                              *)
(*                                                                          *)
(* Jade Alglave, University College London, UK.                             *)
(* Luc Maranget, INRIA Paris-Rocquencourt, France.                          *)
(*                                                                          *)
(* Copyright 2010-present Institut National de Recherche en Informatique et *)
(* en Automatique, ARM Ltd and the authors. All rights reserved.            *)
(*                                                                          *)
(* This software is governed by the CeCILL-B license under French law and   *)
(* abiding by the rules of distribution of free software. You can use,      *)
(* modify and/ or redistribute the software under the terms of the CeCILL-B *)
(* license as circulated by CEA, CNRS and INRIA at the following URL        *)
(* "http://www.cecill.info". We also give a copy in LICENSE.txt.            *)
(****************************************************************************)

(** Test litmus files generated by a [diyone7] command in their first line. *)

type flags = {
  diyone      : string ;
  litmus_dirs : string list ;
}

let directive line =
  match Str.split (Str.regexp "[ \t]+") (String.trim line) with
  | "(*" :: "diyone7" :: args -> begin
      match List.rev args with
      | ["*)"] -> None
      | "*)" :: args -> Some (String.concat " " (List.rev args))
      | _ -> None
    end
  | _ -> None

let rec litmus_files path =
  if Sys.is_directory path then
    Sys.readdir path
    |> Array.to_list
    |> List.sort String.compare
    |> List.map (Filename.concat path)
    |> List.map litmus_files
    |> List.flatten
  else if Filename.check_suffix path ".litmus" then [path]
  else []

let run_diyone flags command =
  let stdout = ref ""
  and stderr = ref "" in
  let shell_command =
    Printf.sprintf "PATH=%s:$PATH; export PATH; exec %s %s"
      (Filename.quote (Filename.dirname flags.diyone))
      (Filename.quote (Filename.basename flags.diyone)) command in
  let status = Command.run_status
    ~stdout:(fun chan -> stdout := String.concat "\n" (Channel.read_lines chan))
    ~stderr:(fun chan -> stderr := String.concat "\n" (Channel.read_lines chan))
    "/bin/sh" ["-c";shell_command] in
  let comment =
    match status,!stderr with
    | 0,"" -> ""
    | 0,stderr -> stderr
    | status,"" -> Printf.sprintf "[%d]" status
    | status,stderr -> Printf.sprintf "[%d]\n%s" status stderr in
  match comment,!stdout with
  | "",stdout -> stdout
  | comment,"" -> Printf.sprintf "(*\n%s\n*)" comment
  | comment,stdout -> Printf.sprintf "(*\n%s\n*)\n%s" comment stdout

let tests flags =
  List.map litmus_files flags.litmus_dirs
  |> List.flatten
  |> List.filter_map
      (fun path ->
        match Filesystem.read_file path Channel.read_lines with
        | first :: expected -> begin
            match directive first with
            | Some command -> Some (path,command,String.concat "\n" expected)
            | None -> None
          end
        | [] -> None)

let run_tests flags =
  let tests = tests flags in
  let failed =
    List.fold_left
      (fun failed (path,command,expected) ->
        let actual = run_diyone flags command in
        if String.trim actual = String.trim expected then failed
        else begin
          Printf.eprintf "%s: generated output differs\nExpected:\n%s\nActual:\n%s\n"
            path expected actual ;
          failed + 1
        end)
      0 tests in
  let tested = List.length tests in
  Printf.printf "Tested %d litmus file%s: %d passed, %d failed\n"
    tested (if tested = 1 then "" else "s") (tested - failed) failed ;
  if failed > 0 then exit 1

let show_tests flags =
  List.iter
    (fun (_,command,_) ->
      Printf.printf "%s %s\n" (Filename.quote flags.diyone) command)
    (tests flags)

let promote_tests flags =
  let tests = tests flags in
  List.iter
    (fun (path,command,_) ->
      let output = run_diyone flags command in
      let directive = Printf.sprintf "(* diyone7 %s *)" command in
      Filesystem.write_file path
        (fun chan -> Printf.fprintf chan "%s\n%s\n" directive (String.trim output)))
    tests ;
  Printf.printf "Promoted %d litmus file%s\n"
    (List.length tests) (if List.length tests = 1 then "" else "s")

let usage = String.concat "\n" [
  Printf.sprintf "Usage: %s [options] DIR... (show|test|promote)"
    (Filename.basename Sys.argv.(0)) ;
  "" ;
  "Recursively test .litmus files beginning with `(* diyone7 ... *)`." ;
  "" ;
  "Commands:" ;
  "  show     Print the diyone7 commands that would be run." ;
  "  test     Compare diyone7 output with each litmus file." ;
  "  promote  Replace each litmus test with the generated output." ;
  "" ;
  "Options:" ;
]

let () =
  let diyone = ref ""
  and dirs = ref [] in
  let options = [
    Args.is_file
      ("-diyone-path",Arg.Set_string diyone,"path to the diyone7 binary");
  ] in
  Arg.parse options (fun arg -> dirs := arg :: !dirs) usage ;
  let exit_with_error msg =
    Printf.printf "%s: %s.\n" Sys.argv.(0) msg ;
    Arg.usage options usage ;
    exit 2 in
  let command,litmus_dirs = match !dirs with
  | command :: dirs -> command,List.rev dirs
  | [] -> exit_with_error "Must provide a command" in
  if litmus_dirs = [] then
    exit_with_error "Must provide at least one directory" ;
  List.iter
    (fun dir ->
      if not (Sys.file_exists dir && Sys.is_directory dir) then
        exit_with_error (Printf.sprintf "Input is not a directory: %s" dir))
    litmus_dirs ;
  if !diyone = "" then
    exit_with_error "Must set -diyone-path" ;
  let flags = { diyone = !diyone; litmus_dirs; } in
  match command with
  | "show" -> show_tests flags
  | "test" -> run_tests flags
  | "promote" -> promote_tests flags
  | _ -> exit_with_error "Must provide one command of: show, test, promote"
