#!/bin/sh

set -eu

if [ $# -eq 0 ]
then
  echo "Usage: $(basename "${0}") <binary> [args]"
  echo ""
  echo "Synopsis: Run the most recently built <binary>.exe or <binary>.native under _build, with args."
  exit 1
fi

readonly binary="${1}"
shift

# A portable version of `realpath` or `readlink -f`.
function absolute_path() {
  readonly prev_pwd="${PWD}"
  cd "${1}"
  pwd
  cd "${prev_pwd}"
}

function most_recent() {
  # List (mtime, path) pairs.
  # Sort them descending by mtime.
  # Take the first of the list.
  # Extract the path back out.
  stat -f '%m %N' $@ \
    | sort --reverse \
    | head -n1 \
    | cut -d' ' -f2
}


readonly build_dir="$(absolute_path "$(dirname "${0}")/../_build")"
readonly paths="$(find "${build_dir}" -name "${binary}.exe" -o -name "${binary}.native")"

if [ ! "${paths}" ]
then
  echo "Could not find binary ${binary} under ${build_dir}"
  exit 1
fi

"$(most_recent ${paths})" $@
