name: Build ASL reference

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'asllib/doc/**'
      - 'asllib/aslspec/**'
      - '.github/workflows/build-asl-reference.yml'

permissions: read-all

# Copy-pasted from https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  make-asldoc:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout tree
        uses: actions/checkout@v7

      - name: Set up OCaml and dependencies
        uses: ./.github/actions/setup-opam
        with:
          ocaml-compiler: dune,zarith,menhir,logs,conf-which
          with-test-dependencies: "false"

      - name: Install python for doclint.py
        run: |
          sudo apt-get install -y python3 # the repos are already updated by setup-opam

      - name: Set up tectonic cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic

      - name: Set up tectonic
        uses: wtfjoke/setup-tectonic@v4

      - name: Build ASL Reference
        run: opam exec -- make asldoc

      - name: Upload PDF
        uses: actions/upload-artifact@v7
        with:
         name: ASL Reference Document
         path: asllib/doc/ASLReference.pdf

  make-asldoc-html:
    runs-on: ubuntu-24.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-bibtex-extra

      - name: Checkout tree
        uses: actions/checkout@v7

      - name: Set up OCaml and dependencies
        uses: ./.github/actions/setup-opam
        with:
          ocaml-compiler: dune,zarith,menhir,logs,conf-which,hevea
          with-test-dependencies: "false"

      - name: Build ASL Reference in HTML
        run: |
          cd asllib/doc
          opam exec -- make html

      - name: Upload HTML
        uses: actions/upload-artifact@v7
        with:
         name: ASL Reference Document in HTML
         path: asllib/doc/HTML
